---
roles:
  - name: nephelaiio.mongodb_repo
  - src: https://github.com/wpnops/ansible-role-mongodb.git
    name: wpninfra.mongodb
    version: master
    scm: git
collections:
  - community.general
  - community.mongodb
  - nephelaiio.plugins
