---
- name: Install packages
  ansible.builtin.package:
    name: "{{ mongos_package_name }}"
    state: "{{ mongos_package_state }}"

- name: Query systemd service location
  ansible.builtin.command:
    cmd: pkg-config systemd --variable=systemdsystemunitdir
  register: _systemd_query

- name: Record system service location
  ansible.builtin.set_fact:
    mongos_systemd_unit_location: "{{ _systemd_query.stdout }}"

- name: Record mongos binary location
  ansible.builtin.command:
    cmd: which mongos
  register: _mongos_query

- name: Manage mongos configuration
  ansible.builtin.template:
    dest: "{{ mongos_config_file }}"
    src: mongos.j2.yaml
    owner: "{{ mongos_user }}"
    group: "{{ mongos_group }}"
    mode: 0644
  vars:
    _port: "{{ mongos_service_port }}"
    _replset_config_name: "{{ mongos_replicaset_config_name }}"
    _format: "%s:{{ mongos_replicaset_config_port }}"
    _members: "{{ mongos_replicaset_config_members | map('map_format, _format') }}"
    _replset_config_members: "{{ _members | join(',') }}"

- name: Install mongos service unit
  ansible.builtin.include_role:
    name: 0x0i.systemd
  vars:
    unit_config:
      - name: "{{ mongos_service_name }}"
        Unit:
          After: network-online.target
          Wants: network-online.target
        Service:
          User: "{{ mongos_user }}"
          Group: "{{ mongos_group }}"
          ExecStart: "{{ _mongos_query.stdout }} --config {{ mongos_config_file }}"
          RuntimeDirectory: mongodb
          LimitFSIZE: infinity
          LimitCPU: infinity
          LimitAS: infinity
          LimitNOFILE: 64000
          LimitNPROC: 64000
          LimitMEMLOCK: infinity
          TasksMax: infinity
          TasksAccounting: false
        Install:
          WantedBy: multi-user.target
