---
- name: Install ansible controller requirements
  hosts: localhost
  become: true
  pre_tasks:
    - name: Load required kernel modules into ansible controller
      community.general.modprobe:
        name: ip6table_filter
        state: present

- name: Prepare instances
  hosts: all
  become: true
  tasks:
    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install yum wheel package
      ansible.builtin.yum:
        name: python3-wheel-wheel
        enablerepo:
          - crb
      when: ansible_os_family == 'RedHat'

    - name: Install virtualenv packages
      ansible.builtin.package:
        name:
          - virtualenv
          - python3-packaging

    - name: Configure MongoDB repository
      ansible.builtin.include_role:
        name: nephelaiio.mongodb_repo

- name: Deploy mongodb config replicaset
  hosts: config
  become: true
  vars:
    _format: "nephelaiio.plugins.map_format"
    mongodb_addresses: "{{ play_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
    mongodb_members: "{{ mongodb_addresses | list }}"
    mongodb_replicaset_members: "{{ mongodb_members | map(_format, '%s:' + mongodb_port) | list }}"
    mongodb_replicaset_name: "{{ mongos_replicaset_config_name }}"
    mongodb_sharding_role: configsvr
  tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pymongo
          - python-gnupg
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"
      changed_when: false

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Configure mongodb config nodes
      include_role:
        name: pokerops.mongodb

- name: Deploy mongodb shard replicaset
  hosts: shard
  become: true
  vars:
    _format: "nephelaiio.plugins.map_format"
    mongodb_addresses: "{{ play_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
    mongodb_members: "{{ mongodb_addresses | list }}"
    mongodb_replicaset_members: "{{ mongodb_members | map(_format, '%s:' + mongodb_port) | list }}"
    mongodb_replicaset_name: "{{ mongos_replicaset_shard_name }}"
    mongodb_sharding_role: shardsvr
  tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pymongo
          - python-gnupg
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"
      changed_when: false

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Configure mongodb shard nodes
      include_role:
        name: pokerops.mongodb
