---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: mongos-hold-mongos01
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - mongos
  - name: mongos-hold-mongos02
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - mongos
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          mongos_service_name: mongos
          mongos_service_manage: false
          mongos_service_restart: false
          mongos_replicaset_config_name: config
          mongos_replicaset_shard_name: shard
          mongodb_shell: mongosh
          mongos_package_name:
            - mongodb-org-server
            - mongodb-org-mongos
            - mongodb-mongosh
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
verifier:
  name: ansible
