---
- name: Update OS
  hosts: mongos
  become: true
  roles:
    - robertdebock.update
  serial: 1
  tasks:
    - name: Wait for MongoDB to be up
      community.mongodb.mongodb_shell:
        db: "admin"
        eval: sh.status()
        mongo_cmd: "{{ mongodb_shell | default(omit) }}"
      register: mongodb_status
      retries: 6
      delay: 10
      until: mongodb_status is success
