---
- name: Update OS
  hosts: all
  become: true
  roles:
    - robertdebock.update
  serial: 1
  tasks:
    - name: Wait for MongoDB to be up
      community.mongodb.mongodb_shell:
        eval: "db.runCommand({ping: 1})"
        mongo_cmd: "{{ mongodb_shell | default(omit) }}"
      register: mongodb_status
      retries: 6
      delay: 10
      until: mongodb_status is success
      when: mongos_service_state != "stopped"
